-- Add hasCallManager to subscription_plans table
ALTER TABLE subscription_plans ADD COLUMN has_call_manager BOOLEAN DEFAULT FALSE;

-- Add canAccessCallManager to users table  
ALTER TABLE users ADD COLUMN can_access_call_manager BOOLEAN DEFAULT FALSE;

-- Create phone_numbers table
CREATE TABLE phone_numbers (
  id SERIAL PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES organizations(id),
  phone_number TEXT NOT NULL UNIQUE,
  friendly_name TEXT,
  area_code TEXT,
  country TEXT DEFAULT 'US',
  number_type TEXT DEFAULT 'local',
  provider TEXT DEFAULT 'twilio',
  provider_sid TEXT,
  provider_account_sid TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  is_call_enabled BOOLEAN DEFAULT TRUE,
  is_sms_enabled BOOLEAN DEFAULT TRUE,
  is_recording_enabled BOOLEAN DEFAULT FALSE,
  voice_url TEXT,
  voice_method TEXT DEFAULT 'POST',
  sms_url TEXT,
  sms_method TEXT DEFAULT 'POST',
  status_callback_url TEXT,
  voicemail_enabled BOOLEAN DEFAULT TRUE,
  call_forwarding_enabled BOOLEAN DEFAULT FALSE,
  call_forwarding_number TEXT,
  business_hours JSONB DEFAULT '{"enabled": false}',
  after_hours_action TEXT DEFAULT 'voicemail',
  after_hours_number TEXT,
  monthly_cost DECIMAL(10,4) DEFAULT '0',
  usage_cost DECIMAL(10,4) DEFAULT '0',
  assigned_to INTEGER REFERENCES users(id),
  department TEXT,
  purpose TEXT,
  purchased_at TIMESTAMP DEFAULT NOW(),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Create call_records table
CREATE TABLE call_records (
  id SERIAL PRIMARY KEY,
  organization_id INTEGER NOT NULL REFERENCES organizations(id),
  phone_number_id INTEGER REFERENCES phone_numbers(id),
  call_sid TEXT NOT NULL UNIQUE,
  parent_call_sid TEXT,
  from_number TEXT NOT NULL,
  to_number TEXT NOT NULL,
  from_formatted TEXT,
  to_formatted TEXT,
  direction TEXT NOT NULL,
  call_type TEXT DEFAULT 'voice',
  status TEXT NOT NULL,
  start_time TIMESTAMP,
  answer_time TIMESTAMP,
  end_time TIMESTAMP,
  duration INTEGER DEFAULT 0,
  billable_duration INTEGER DEFAULT 0,
  call_quality TEXT,
  price DECIMAL(10,4) DEFAULT '0',
  price_unit TEXT DEFAULT 'USD',
  handled_by INTEGER REFERENCES users(id),
  assigned_to INTEGER REFERENCES users(id),
  purpose TEXT,
  notes TEXT,
  tags TEXT[],
  priority TEXT DEFAULT 'normal',
  customer_id INTEGER REFERENCES customers(id),
  lead_id INTEGER REFERENCES leads(id),
  project_id INTEGER REFERENCES projects(id),
  was_recorded BOOLEAN DEFAULT FALSE,
  was_transferred BOOLEAN DEFAULT FALSE,
  was_conference BOOLEAN DEFAULT FALSE,
  had_voicemail BOOLEAN DEFAULT FALSE,
  error_code TEXT,
  error_message TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create call_recordings table
CREATE TABLE call_recordings (
  id SERIAL PRIMARY KEY,
  call_record_id INTEGER NOT NULL REFERENCES call_records(id) ON DELETE CASCADE,
  organization_id INTEGER NOT NULL REFERENCES organizations(id),
  recording_sid TEXT NOT NULL UNIQUE,
  recording_url TEXT NOT NULL,
  recording_duration INTEGER DEFAULT 0,
  recording_size INTEGER DEFAULT 0,
  recording_format TEXT DEFAULT 'mp3',
  recording_channels TEXT DEFAULT 'mono',
  recording_source TEXT DEFAULT 'DialVerb',
  is_transcribed BOOLEAN DEFAULT FALSE,
  transcription_status TEXT DEFAULT 'pending',
  is_encrypted BOOLEAN DEFAULT FALSE,
  encryption_key TEXT,
  local_file_path TEXT,
  cloudinary_url TEXT,
  retention_period INTEGER DEFAULT 90,
  expires_at TIMESTAMP,
  consent_given BOOLEAN DEFAULT FALSE,
  consent_timestamp TIMESTAMP,
  legal_hold BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);
